blank_issues_enabled: true
contact_links:
  - name: 🆘 Написать в поддержку VK ID
    url: devsupport@corp.vk.com
    about: Сообщите о проблемах с авторизацией через VK ID, не связанных с работой SDK.